const CFG=window.GAME_CONFIG,DICT=window.GAME_DICTIONARY,$=id=>document.getElementById(id);
let guesses=[];let myGuesses=[];let supabaseClient=null;
try{$('name').value=localStorage.getItem('mh-name')||''}catch(error){console.error('Impossible de charger le nom enregistré.',error)}
try{const saved=JSON.parse(localStorage.getItem('mh-my-guesses')||'[]');if(Array.isArray(saved))myGuesses=saved}catch(error){console.error('Impossible de charger votre historique local.',error)}
const norm=s=>String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9' -]/g,'').replace(/\s+/g,' ');
function lev(a,b){a=norm(a);b=norm(b);const m=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=m[0];m[0]=i;for(let j=1;j<=b.length;j++){const t=m[j];m[j]=Math.min(m[j]+1,m[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=t}}return m[b.length]}
function label(d){return [...CFG.labels].sort((a,b)=>b.min-a.min).find(x=>d>=x.min)?.label||'Glacial'}
function evaluate(raw){const w=norm(raw),exact=DICT.exactAnswers.map(norm);if(exact.includes(w))return 100;const near=Math.max(...exact.map(x=>1-lev(w,x)/Math.max(w.length,x.length)));if(near>.88)return Math.min(99,Math.round(82+near*18));for(const[k,v]of Object.entries(DICT.overrides))if(norm(k)===w)return v;let score=5;for(const g of DICT.concepts)for(const term of g.words){const t=norm(term);if(w===t)score=Math.max(score,g.score);else if(w.includes(t)||(t.includes(w)&&w.length>3))score=Math.max(score,g.score-4);else{const sim=1-lev(w,t)/Math.max(w.length,t.length);if(sim>.78)score=Math.max(score,Math.round(g.score*sim))}}return Math.min(99,Math.max(0,Math.round(score)))}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function render(){const best={};for(const g of guesses)if(!best[g.name]||g.degree>best[g.name].degree)best[g.name]=g;const leaders=Object.values(best).sort((a,b)=>b.degree-a.degree).slice(0,30);$('leaders').innerHTML=leaders.length?leaders.map((g,i)=>`<div class="rank"><span class="num">${i+1}</span><span class="rmain"><b>${esc(g.name)}</b><small>${esc(g.label)}</small></span><span class="degree">${g.degree}°</span></div>`).join(''):'<div class="empty">Aucune proposition pour le moment.</div>';$('history').innerHTML=myGuesses.length?[...myGuesses].reverse().slice(0,25).map(g=>`<div class="rank"><span class="rmain"><b>${esc(g.word)}</b><small>${esc(g.label)} · ${new Date(g.date).toLocaleString('fr-FR')}</small></span><span class="degree">${g.degree}°</span></div>`).join(''):'<div class="empty">Vos propositions apparaîtront ici, uniquement sur cet appareil.</div>'}
function setNotice(message){$('notice').textContent=message}
async function loadSharedGuesses(){const{data,error}=await supabaseClient.rpc('get_game_leaderboard');if(error)throw error;guesses=data;render()}
async function connectToSharedGame(){const{url,anonKey}=CFG.supabase||{};if(!url||!anonKey){setNotice('Classement non configuré : renseignez l’URL et la clé anon Supabase dans config.js.');return}if(!window.supabase?.createClient){setNotice('La bibliothèque Supabase ne s’est pas chargée. Vérifiez votre connexion internet puis rechargez la page.');return}supabaseClient=window.supabase.createClient(url,anonKey);try{await loadSharedGuesses();setNotice('Classement partagé · actualisation automatique.');$('submit').disabled=false;setInterval(async()=>{try{await loadSharedGuesses()}catch(error){console.error('Erreur lors de l’actualisation du classement:',error)}},15000)}catch(error){setNotice('Impossible de charger le classement partagé. Vérifiez la configuration Supabase.');console.error('Erreur de connexion au classement Supabase:',error)}}
function apply(){const s=CFG.site;document.documentElement.style.setProperty('--p',s.primary);document.documentElement.style.setProperty('--s',s.secondary);document.documentElement.style.setProperty('--a',s.accent);document.documentElement.style.setProperty('--bg',s.background);$('title').innerHTML=esc(s.title).replace('2 Novembre','<br>2 Novembre');$('subtitle').textContent=s.subtitle;const now=new Date(),started=now>=new Date(s.startDate),revealed=now>=new Date(s.revealDate),today=iso(now);let idx=CFG.clues.findLastIndex(c=>c.date<=today);if(idx<0)idx=0;$('status').textContent=revealed?'Thème révélé':started?'Enquête en cours':'Bientôt';$('clueNo').textContent=started?`Indice ${idx+1} / ${CFG.clues.length}`:'Verrouillé';$('clue').textContent=revealed?s.revealMessage:(started?`« ${CFG.clues[idx].text} »`:'La devinette n’est pas encore ouverte.');$('archive').innerHTML=CFG.clues.map(c=>`<div class="day ${started&&c.date<=today?'on':''}"><b>${new Date(c.date+'T12:00:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'short'})}</b><br>${c.date<=today?'Indice disponible':'Verrouillé'}</div>`).join('');render();paint()}
function tick(){const d=Math.max(0,new Date(CFG.site.revealDate)-new Date());$('dd').textContent=String(Math.floor(d/86400000)).padStart(2,'0');$('hh').textContent=String(Math.floor(d/3600000)%24).padStart(2,'0');$('mm').textContent=String(Math.floor(d/60000)%60).padStart(2,'0');$('ss').textContent=String(Math.floor(d/1000)%60).padStart(2,'0')}
async function submitGuess(){const name=$('name').value.trim(),word=$('word').value.trim();if(!name||!word)return alert('Renseignez votre nom complet ou pseudo et une proposition.');try{localStorage.setItem('mh-name',name)}catch(error){console.error('Impossible d’enregistrer le nom sur cet appareil.',error)}if(!supabaseClient)return setNotice('Le classement partagé n’est pas disponible. Votre proposition n’a pas été enregistrée.');const degree=evaluate(word),g={name,word,degree,label:label(degree)};$('submit').disabled=true;try{const{error}=await supabaseClient.from('game_guesses').insert(g);if(error)throw error;const localGuess={word,degree,label:g.label,date:new Date().toISOString()};myGuesses.push(localGuess);try{localStorage.setItem('mh-my-guesses',JSON.stringify(myGuesses))}catch(storageError){console.error('La proposition a été enregistrée, mais impossible de sauvegarder votre historique local.',storageError)}render();$('degree').textContent=degree+'°';$('heat').textContent=degree===100?'Vous avez trouvé le thème.':g.label;$('bar').style.width=degree+'%';$('result').classList.add('show');$('word').value='';setNotice('Proposition enregistrée. Votre historique reste sur cet appareil.');try{await loadSharedGuesses()}catch(refreshError){console.error('La proposition a été enregistrée, mais le classement ne s’est pas actualisé:',refreshError)}}catch(error){if(error.code==='23505'){setNotice('Ce nom ou pseudo a déjà proposé aujourd’hui. Chaque personne doit utiliser un identifiant qui lui est propre.')}else{setNotice('Échec de l’enregistrement. Votre proposition n’a pas été sauvegardée. Réessayez.');console.error('Erreur lors de l’enregistrement Supabase:',error)}}finally{$('submit').disabled=false}}
$('submit').onclick=submitGuess;$('word').addEventListener('keydown',e=>{if(e.key==='Enter')$('submit').click()});
function paint(){const c=$('scratch'),box=c.parentElement,ctx=c.getContext('2d'),r=box.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);c.width=r.width*dpr;c.height=r.height*dpr;ctx.scale(dpr,dpr);const g=ctx.createLinearGradient(0,0,r.width,r.height);g.addColorStop(0,'#d4a6df');g.addColorStop(.5,'#846b94');g.addColorStop(1,'#ef9c5c');ctx.fillStyle=g;ctx.fillRect(0,0,r.width,r.height);ctx.globalCompositeOperation='destination-out';let on=false,m=0;const pos=e=>{const q=e.touches?e.touches[0]:e,b=c.getBoundingClientRect();return{x:q.clientX-b.left,y:q.clientY-b.top}},draw=e=>{if(!on)return;e.preventDefault();const p=pos(e);ctx.beginPath();ctx.arc(p.x,p.y,28,0,Math.PI*2);ctx.fill();if(++m>3)$('hint').style.opacity=0};['mousedown','touchstart'].forEach(x=>c.addEventListener(x,e=>{on=true;draw(e)},{passive:false}));['mousemove','touchmove'].forEach(x=>c.addEventListener(x,draw,{passive:false}));['mouseup','mouseleave','touchend'].forEach(x=>c.addEventListener(x,()=>on=false))}
setInterval(tick,500);tick();apply();connectToSharedGame();
